services:
  postgres:
    container_name: repodash-postgres
    image: postgres:16.5-alpine3.20
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=db
    ports:
      - "5441:5432"
    restart: always
